[package]
name = "kafka-consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = {version = "0.36.2", features = ["cmake-build"], default-features = false }
clap = "2.18.0"
env_logger = "0.9.0"
log = "0.4.8"
