[package]
name = "kafka-consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = {version = "0.36.2", features = ["cmake-build"], default-features = false }
clap = "4.5.8"
env_logger = "0.11.3"
log = "0.4.22"